# -*- coding: utf-8 -*-
"""keras-mnist-sagemaker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7tAglsNalivv34beXL5gGnB9WEYBCkW

# Training and deploying our Keras CNN on SageMaker

'''bash
!pip install sagemaker awscli boto3 --upgrade
!aws configure
#### Enter AWS Access Key, Secret Key, default region
'''


'''python

import boto3
import sagemaker

session = sagemaker.Session(
    boto_session=boto3.Session(
        aws_access_key_id="YOUR_KEY",
        aws_secret_access_key="YOUR_SECRET",
        region_name="us-east-1"
    )
)

role = "arn:aws:iam::123456789012:role/YourSageMakerRole"
'''

Based on https://aws.amazon.com/blogs/machine-learning/train-and-deploy-keras-models-with-tensorflow-and-apache-mxnet-on-amazon-sagemaker/

Modified Keras MNIST example from mnist-train-cnn.py script that you must upload into this Notebook's directory:  same code as first CNN, but with a extra stuff to allow hyperparameters to be passed in as arguments from SageMaker.
"""

import sagemaker

sess = sagemaker.Session()
role = sagemaker.get_execution_role()

"""## Save the MNIST dataset to disk


"""

import os
import keras
import numpy as np
from keras.datasets import mnist
(x_train, y_train), (x_val, y_val) = mnist.load_data()

os.makedirs("./data", exist_ok = True)

np.savez('./data/training', image=x_train, label=y_train)
np.savez('./data/validation', image=x_val, label=y_val)

"""## Upload MNIST data to S3

Note that sess.upload_data automatically creates an S3 bucket that meets the security criteria of starting with "sagemaker-".
"""

prefix = 'keras-mnist'

training_input_path   = sess.upload_data('data/training.npz', key_prefix=prefix+'/training')
validation_input_path = sess.upload_data('data/validation.npz', key_prefix=prefix+'/validation')

print(training_input_path)
print(validation_input_path)

"""## Test out our CNN training script locally on the notebook instance

Test run a single epoch, just to make sure the script works before spending money on P3 instances to train it further.
"""

!pygmentize mnist-train-cnn.py

from sagemaker.tensorflow import TensorFlow

tf_estimator = TensorFlow(entry_point='mnist-train-cnn.py',
                          role=role,
                          instance_count=1,
                          instance_type='local',
                          framework_version='1.12',
                          py_version='py3',
                          script_mode=True,
                          hyperparameters={'epochs': 1}
                         )

tf_estimator.fit({'training': training_input_path, 'validation': validation_input_path})

"""## Train on a GPU instance with 10 epochs

Now that it works, can start spending money on beefier servers to train CNN over more epochs.
"""

tf_estimator = TensorFlow(entry_point='mnist-train-cnn.py',
                          role=role,
                          instance_count=1,
                          instance_type='ml.p3.2xlarge',
                          framework_version='1.12',
                          py_version='py3',
                          script_mode=True,
                          hyperparameters={
                              'epochs': 10,
                              'batch-size': 32,
                              'learning-rate': 0.001}
                         )

tf_estimator.fit({'training': training_input_path, 'validation': validation_input_path})

"""## Deploy the model

To keep costs low, deploy model to a C5 instance to make inferences. Could also use GPU instances which would be faster, but at higher cost. Note Elastic Inference accelerator here.
"""

import time

tf_endpoint_name = 'keras-tf-mnist-'+time.strftime("%Y-%m-%d-%H-%M-%S", time.gmtime())

tf_predictor = tf_estimator.deploy(initial_instance_count=1,
                         instance_type='ml.c5.large',
                         accelerator_type='ml.eia1.medium',
                         endpoint_name=tf_endpoint_name)

"""## Make predictions with the deployed model"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import random
import matplotlib.pyplot as plt

num_samples = 5
indices = random.sample(range(x_val.shape[0] - 1), num_samples)
images = x_val[indices]/255
labels = y_val[indices]

for i in range(num_samples):
    plt.subplot(1,num_samples,i+1)
    plt.imshow(images[i].reshape(28, 28), cmap='gray')
    plt.title(labels[i])
    plt.axis('off')

prediction = tf_predictor.predict(images.reshape(num_samples, 28, 28, 1))['predictions']
prediction = np.array(prediction)
predicted_label = prediction.argmax(axis=1)
print('Predicted labels are: {}'.format(predicted_label))

"""## Clean up the deployment endpoint"""

sess.delete_endpoint(endpoint_name=tf_endpoint_name)

"""## Find the best hyperparameters with Automatic Model Tuning

This is by far the most expensive part of this exercise; Use a fair amount of time on P3 instances here.  High AWS costs for rest of this notebook!!
"""

tf_estimator = TensorFlow(entry_point='mnist-train-cnn.py',
                          role=role,
                          instance_count=1,
                          instance_type='ml.p3.2xlarge',
                          framework_version='1.12',
                          py_version='py3',
                          script_mode=True
                         )

from sagemaker.tuner import IntegerParameter, CategoricalParameter, ContinuousParameter, HyperparameterTuner

hyperparameter_ranges = {
    'epochs':        IntegerParameter(5, 20),
    'learning-rate': ContinuousParameter(0.0001, 0.1, scaling_type='Logarithmic'),
    'batch-size':    IntegerParameter(32, 1024),
}

objective_metric_name = 'val_acc'
objective_type = 'Maximize'
metric_definitions = [{'Name': 'val_acc', 'Regex': 'val_acc: ([0-9\\.]+)'}]

tuner = HyperparameterTuner(tf_estimator,
                            objective_metric_name,
                            hyperparameter_ranges,
                            metric_definitions,
                            max_jobs=10,
                            max_parallel_jobs=2,
                            objective_type=objective_type)

tuner.fit({'training': training_input_path, 'validation': validation_input_path})

"""## Deploy the best model"""

import time

tf_endpoint_name = 'keras-tf-mnist-'+time.strftime("%Y-%m-%d-%H-%M-%S", time.gmtime())

tf_predictor = tuner.deploy(initial_instance_count=1,
                         instance_type='ml.c5.large',
                         accelerator_type='ml.eia1.medium',
                         endpoint_name=tf_endpoint_name)

"""## Predict again"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import random
import matplotlib.pyplot as plt

num_samples = 5
indices = random.sample(range(x_val.shape[0] - 1), num_samples)
images = x_val[indices]/255
labels = y_val[indices]

for i in range(num_samples):
    plt.subplot(1,num_samples,i+1)
    plt.imshow(images[i].reshape(28, 28), cmap='gray')
    plt.title(labels[i])
    plt.axis('off')

prediction = tf_predictor.predict(images.reshape(num_samples, 28, 28, 1))['predictions']
prediction = np.array(prediction)
predicted_label = prediction.argmax(axis=1)
print('Predicted labels are: {}'.format(predicted_label))

"""## Clean up"""

sess.delete_endpoint(endpoint_name=tf_endpoint_name)

"""## Shut down the notebook instance too!!!!"""

