# -*- coding: utf-8 -*-
"""TF-IDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctxTp9GVBdiTs_Wf_lskVkt7QxPUGzf2

## PySpark: Subset of Wikipedia data:
"""

rawdata = spark.read.options(sep="\t").csv("s3://aws-emr-studio-159107795666-us-east-1/1733157099735/subset-small.tsv")
rawdata.show()

# DOWNLOAD DATA: bash>
!pip install awscli
!aws s3 cp s3://aws-emr-studio-159107795666-us-east-1/1733157099735/subset-small.tsv subset-small.tsv

rawdata = spark.read.options(sep="\t").csv("subset-small.tsv")
rawdata.show()

!apt-get -y install openjdk-11-jdk
!pip install pyspark==3.5.1


from pyspark.sql import SparkSession

spark = (SparkSession.builder
         .appName("ColabSpark")
         .getOrCreate())


rawdata = spark.read.options(sep="\t").csv("s3://aws-emr-studio-159107795666-us-east-1/1733157099735/subset-small.tsv")
rawdata.show()

"""### There are no column names in source data, so they must be manually added:"""

articles = rawdata.toDF("ID", "Title", "Time", "Document")
articles.show()

"""Next Data is cleaned:
TF/IDF can't handle null documents, so first check for that.
"""

articles.filter(articles.Document.isNull()).count()

"""

```
# This is formatted as code
```

There is one null document. As there is only one and it's clearly corrupt, just remove it!"""

cleanedArticles = articles.filter(articles.Document.isNotNull())
cleanedArticles.filter(articles.Document.isNull()).count()

"""TF/IDF wants numbers, not words. So NEXT:  pre-process data before any algorithms can be run on it.
1st: Tokenize the articles to split them up into words, and store them in a sparse vector that is now a numeric representation of the words in each article.
"""

from pyspark.ml.feature import HashingTF, IDF, Tokenizer

tokenizer= Tokenizer(inputCol="Document", outputCol="words")
wordsData = tokenizer.transform(cleanedArticles)

hashingTF = HashingTF(inputCol="words", outputCol="rawFeatures")
featurizedData = hashingTF.transform(wordsData)
featurizedData.show()

"""The hashing operation computed **term frequencies** by storing how often each hashed word occured in each article. So we have TF, ...
...but we want TF/IDF scores for every term in every document. We'll store these final scores in a new column called "features", which is a sparse vector containing TF/IDF scores for each feature.
"""

idf = IDF(inputCol="rawFeatures", outputCol="features")
idfModel = idf.fit(featurizedData)
rescaledData = idfModel.transform(featurizedData)

rescaledData.show()

"""Use this to do a search for the term "Gettysburg". Again, numbers are needed, not words, so the first task is to get the hash value for "Gettysburg"
"""

from pyspark.sql.types import *

schema = StructType([StructField("words", ArrayType(StringType()))])

df = spark.createDataFrame(([[["gettysburg"]]]), schema).toDF("words")
df.show()

gettysburg = hashingTF.transform(df)
gettysburg.show()

featureVec = gettysburg.select('rawFeatures').collect()
print(featureVec)

gettysburgID = int(featureVec[0].rawFeatures.indices[0])
print(gettysburgID)

"""This is the magic number that represents "Gettysburg". Now add another column called "score": that just extracts the TF/IDF value for Gettysburg for each document."""

from pyspark.sql.types import FloatType
from pyspark.sql.functions import udf

termExtractor = udf(lambda x: float(x[gettysburgID]), FloatType())
gettysburgDF = rescaledData.withColumn('score', termExtractor(rescaledData.features))

gettysburgDF.show()

"""Finally, sort articles by score, revealing the most relevant articles for Gettysburg!"""

sortedResults = gettysburgDF.filter("score > 0").orderBy('score', ascending=False).select('ID', 'Title', 'Document', 'score')
sortedResults.show(truncate=100)

