# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='scrumboard.Project'),
            preserve_default=False,
        ),
    ]
