// @flow
export default {
  LOAD_SUBMISSION_DETAIL: 'LOAD_SUBMISSION_DETAIL',
  LOAD_SUBMISSION_DETAIL_SUCCESS: 'LOAD_SUBMISSION_DETAIL_SUCCESS',
  LOAD_SUBMISSION_DETAIL_FAILURE: 'LOAD_SUBMISSION_DETAIL_FAILURE',

  LIST_SUBMISSIONS: 'LIST_SUBMISSIONS',
  LIST_SUBMISSIONS_SUCCESS: 'LIST_SUBMISSIONS_SUCCESS',
  LIST_SUBMISSIONS_FAILURE: 'LIST_SUBMISSIONS_FAILURE',

  SET_CURRENT_SUBMISSION: 'SET_CURRENT_SUBMISSION'
};
