// @flow
export default {
  LOAD_CIF_DETAIL: 'LOAD_CIF_DETAIL',
  LOAD_CIF_DETAIL_SUCCESS: 'LOAD_CIF_DETAIL_SUCCESS',
  LOAD_CIF_DETAIL_FAILURE: 'LOAD_CIF_DETAIL_FAILURE',

  LIST_CIFS: 'LIST_CIFS',
  LIST_CIFS_SUCCESS: 'LIST_CIFS_SUCCESS',
  LIST_CIFS_FAILURE: 'LIST_CIFS_FAILURE',

  SET_CURRENT_CIF: 'SET_CURRENT_CIF'
};
