// @flow
export default {
  LOAD_CERTIFICATION_DETAIL: 'LOAD_CERTIFICATION_DETAIL',
  LOAD_CERTIFICATION_DETAIL_SUCCESS: 'LOAD_CERTIFICATION_DETAIL_SUCCESS',
  LOAD_CERTIFICATION_DETAIL_FAILURE: 'LOAD_CERTIFICATION_DETAIL_FAILURE',

  LIST_CERTIFICATIONS: 'LIST_CERTIFICATIONS',
  LIST_CERTIFICATIONS_SUCCESS: 'LIST_CERTIFICATIONS_SUCCESS',
  LIST_CERTIFICATIONS_FAILURE: 'LIST_CERTIFICATIONS_FAILURE',

  SET_CURRENT_CERTIFICATION: 'SET_CURRENT_CERTIFICATION'
};
