FROM example-base:latest
RUN pip install -r django/requirements.txt; pip install gunicorn
WORKDIR django/
RUN ./manage.py makemigrations; ./manage.py migrate
EXPOSE 8000
CMD gunicorn --bind 0.0.0.0:8000 -w 2 djangoproj.wsgi